DeveloperSthan/DeveloperSthan/DeveloperSthan/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('item/', include('item.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DeveloperSthan/DeveloperSthan/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
]

DeveloperSthan/DeveloperSthan/item/urls.py
from django.urls import path

from . import views

app_name= 'item'

urlpatterns = [
    path('<int:pk>/' , views.detail , name='detail'),
    #path('project/<int:pk>/', views.project_detail, name='project'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('project/<int:pk>/', views.edit_project, name='edit_project'),
]

DeveloperSthan/DeveloperSthan/core/models.py
from django.db import models

# Create your models here.

DeveloperSthan/DeveloperSthan/item/models.py
from django.db import models

class Category (models.Model):
    name=models.CharField(max_length=255)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def __str__(self):
        return self.name
    
class Item(models.Model):
    category=models.ForeignKey(Category, related_name='items',on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    is_open_for_part_time_work =models.BooleanField(default=False)

    is_open_for_full_time_work =models.BooleanField(default=False)
    is_open_for_gigs =models.BooleanField(default=False)
    is_open_for_internships =models.BooleanField(default=False)
    image=models.ImageField(upload_to='item_images',blank=True, null=True)
    video = models.FileField(upload_to='item_videos', blank=True, null=True)


    def __str__(self):
        return self.name
    
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    cover_image = models.ImageField(upload_to='project_images', blank=True, null=True)
    demo_link = models.URLField(max_length=200)
    demo_video = models.FileField(upload_to='project_videos', blank=True, null=True)

    def __str__(self):
        return self.title

DeveloperSthan/DeveloperSthan/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

DeveloperSthan/DeveloperSthan/item/forms.py
from django import forms
from .models import Project

from .models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'is_open_for_part_time_work', 'image', 'video')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'is_open_for_part_time_work': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
            'video': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })  
        }

class EditProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('title', 'description', 'cover_image', 'demo_link', 'demo_video')
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'INPUT_CLASSES',  # Make sure to replace 'INPUT_CLASSES' with the actual CSS class you want to use
            }),
            'description': forms.Textarea(attrs={
                'class': 'INPUT_CLASSES',
            }),
            'cover_image': forms.FileInput(attrs={
                'class': 'INPUT_CLASSES',
            }),
            'demo_link': forms.URLInput(attrs={
                'class': 'INPUT_CLASSES',
            }),
            'demo_video': forms.FileInput(attrs={
                'class': 'INPUT_CLASSES',
            })
        }

DeveloperSthan/DeveloperSthan/core/views.py
from django.shortcuts import render, redirect
from .forms import SignupForm

from item.models import Category, Item

def index(request):
    items = Item.objects.filter(is_open_for_gigs=False)[0:6]
    categories=Category.objects.all()

    return render(request, 'core/index.html',{
        'categories': categories,
        'items':items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'core/signup.html', {
        'form': form
    })
    

DeveloperSthan/DeveloperSthan/item/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect

from .models import Project  # Import the Project model from your app
from .forms import EditProjectForm  # Import the EditProjectForm from your forms module


from .forms import  EditItemForm
from .models import Category, Item
from .models import Item,Project

def detail(request,pk):
    item = get_object_or_404(Item ,pk=pk)
    related_items = Item.objects.filter(category=item.category).exclude(pk=pk)[0:3]

    return render(request,'item/detail.html',{
        'item':item ,
        'related_items' :related_items
        })


# def project_detail(request, pk):
#     project = get_object_or_404(Project, pk=pk)
#     related_projects = Project.objects.filter(category=project.category).exclude(pk=pk)[:3]

#     return render(request, 'item/project.html', {
#         'project': project,
#         'related_projects': related_projects
#     })
@login_required
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:detail', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Edit item',
    })


@login_required
def edit_project(request, pk):
    project = get_object_or_404(Project, pk=pk)

    if request.method == 'POST':
        form = EditProjectForm(request.POST, request.FILES, instance=project)

        if form.is_valid():
            form.save()

            return redirect('project:detail', pk=project.pk)  # Replace 'project:detail' with the actual URL name for your project detail view
    else:
        form = EditProjectForm(instance=project)

    return render(request, 'item/project.html', {
        'form': form,
        'title': 'Edit Project',
    })

DeveloperSthan/DeveloperSthan/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width", initil-scale="1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %} {% endblock %} |DeveloperSthan</title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">DeveloperSthan</a>

            <div class="space-x-6">
                <a href="#" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                {% if request.user.is_authenticated %}
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                {% else %}
                    <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>
                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock  %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About Us </h3>

                <p class="text-lg text-gray-500"> DeveloperSthan is a place where you can showcase your profile for different jobs.</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu </h3>

                <ul class="space-y-2">
                    <li><a href="#" class=" text-ld text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'core:contact' %}" class=" text-ld text-teal-500 hover:text-teal-700">Contact</a></li>
                    <li><a href="#" class=" text-ld text-teal-500 hover:text-teal-700">Privacy Policy</a></li>
                    <li><a href="#" class=" text-ld text-teal-500 hover:text-teal-700">Terms of uses</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

DeveloperSthan/DeveloperSthan/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %} Contact {% endblock %}

{% block content %}
    <h1>the contact page</h1>
{% endblock  %}

DeveloperSthan/DeveloperSthan/core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %} Welcome {% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest Profiles</h2>

        <div class="grid grid-cols-6 gap-10">
            {% for item in items %}
                <div> 
                    <a href="{% url 'item:detail' item.id %}">
                        <div>
                            <img src="{{item.image.url}}" class="rounded-t-xl">
                        </div>                    

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Description:{{item.description}}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div> 
                <a href="#">                   
                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ category.name }}</h2>
                        <p class="text-gray-500">{{category.items.count}} profiles</p>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

DeveloperSthan/DeveloperSthan/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

DeveloperSthan/DeveloperSthan/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

DeveloperSthan/DeveloperSthan/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title%}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-7 gap-2">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" class = "rounded-xl">
    </div>

    <div class="col-span-3 p-6 bg-gray-100 rounded-xl">
        <h1 class=" mb-6 text-3xl ">{{item.name}}</h1>
        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description: </strong><br>
                {{item.description}}
            </p>
        {% endif %}
        {% if item.video %}
        <p class="text-gray-900"><strong>Video: </strong><br> 
            <video controls width="100%">
                <source src="{{ item.video.url }}" type="video/mp4">
                Your browser does not support the video tag.
            </video>
        </p>
    {% endif %}

    <a href="{% url 'item:edit_project' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-blue-500 text-white rounded-xl hover:bg-teal-700">Add Projects</a>



        {% comment %} {% if request.user == item.created_by %}
            <div class = "mt-6 p-6 bg-white rounded-xl">
                <p>This is your item!</p> {% endcomment %}

                {% comment %} <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a> 
            </div>
        {% else %} {% endcomment %}
        <a href="{% url 'item:edit' item.id %}" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl">Edit</a>
        <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Contact developer </a>

        {% comment %} {% endif %} {% endcomment %}
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related Profiles</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div> 
                <a href="{% url 'item:detail' item.id %}">
                    <div>
                        <img src="{{item.image.url}}" class="rounded-t-xl">
                    </div>                    

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Description:{{item.description}}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

DeveloperSthan/DeveloperSthan/item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}

    <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
</form>
{% endblock %}

DeveloperSthan/DeveloperSthan/item/templates/item/project.html
<!-- project_detail.html -->

{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>{{ project.title }}</h1>
    <p>{{ project.description }}</p>
    {% if project.cover_image %}
        <img src="{{ project.cover_image.url }}" alt="{{ project.title }}" class="img-fluid">
    {% endif %}
    <p><a href="{{ project.demo_link }}" target="_blank">Demo Link</a></p>
    
    {% if project.demo_video %}
        <p><a href="{{ project.demo_video.url }}" target="_blank">Demo Video</a></p>
    {% endif %}
</div>
{% endblock %}